### ISSUE TITLE
Constant title rename please!

### ISSUE THREAD

**Issue by giraffes-exist** [ossstudenthelper/cocktaildbpy#1]
https://github.com/ossstudenthelper/cocktaildbpy/blob/407cf1f0d2257e8ffcfe2fa65d3183a0b21e740c/cocktaildbpy/constants.py#L52

LIGHT_RUM = 'Light Rum'

**Comment by giraffes-exist** [comment]
https://github.com/ossstudenthelper/cocktaildbpy/blob/407cf1f0d2257e8ffcfe2fa65d3183a0b21e740c/cocktaildbpy/constants.py#L73

please change the special character to "N"

**Comment by ossstudenthelper** [comment]
Fixed
